### ISSUE TITLE
[NEW FEATURE IN THE WORKS] Dask Distributed Computations!

### ISSUE THREAD

**Issue by windowshopr** [ahmedfgad/GeneticAlgorithmPython#126]
Hey @ahmedfgad !!

I recently started working on a further extension to the recent parallel processing update, by trying to implement Dask, a distributed computation library. So rather than being stuck with using just your one machine, you could potentially send some `fitness_func` calculations to your cluster of machines/processes to introduce even more solutions calculated at once by using many machines!

I've made a fork located [here](https://github.com/windowshopr/GeneticAlgorithmPython/blob/master/pygad.py) where you can see some changes I've made so far.

The places to look are:
1. The top imports of course
2. Line 888 and 889
3. Lines 1219 to 1255

As you'll see, rather than passing in, for example, `["process", 4]` as a parameter to engage multiprocessing, the user can pass in a Dask `Client` object. The code from there runs the Dask logic in `pygad.py`, checking if the object is in fact a `Client` object, and if so, perform the stuff on lines 1219 to 1255.

I'm stuck however, with what looks like a `pickle` related bug but I am having a tough time debugging it. The closest issue I've found is [here](https://github.com/joblib/joblib/issues/1073), which is close, but not exact/I have no idea what they're talking about haha.

The full traceback I see looks like this:

```
Traceback (most recent call last):
  File "Z:\Python_Projects\Stock_Options_Trading\PredictionIntervals\main.py", line 263, in <module>
    ga_instance.run()
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python310\lib\site-packages\pygad\pygad.py", line 1361, in run
    self.last_generation_fitness = self.cal_pop_fitness()
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python310\lib\site-packages\pygad\pygad.py", line 1251, in cal_pop_fitness
    fitnesses = compute(*delayed_results)
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python310\lib\site-packages\dask\base.py", line 603, in compute
    results = schedule(dsk, keys, **kwargs)
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python310\lib\site-packages\distributed\client.py", line 3000, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python310\lib\site-packages\distributed\client.py", line 2174, in gather
    return self.sync(
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python310\lib\site-packages\distributed\utils.py", line 338, in sync
    return sync(
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python310\lib\site-packages\distributed\utils.py", line 405, in sync
    raise exc.with_traceback(tb)
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python310\lib\site-packages\distributed\utils.py", line 378, in f
    result = yield future
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python310\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python310\lib\site-packages\distributed\client.py", line 2037, in _gather
    raise exception.with_traceback(traceback)
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python310\lib\site-packages\distributed\protocol\pickle.py", line 73, in loads
    return pickle.loads(x)
ModuleNotFoundError: No module named 'utils'
```

...which doesn't match with that last line at all? So something tells me, it's because the `future` objects created by Dask before they get computed aren't "pickleable", but that's just a guess, I have no idea.

I have created a minimal working example of how to implement Dask to perform some delayed computations just in case you are not familiar with it. To get this working from scratch:

1. `pip install dask[complete]`
2. Open a terminal window and run `dask-scheduler` to start the scheduler
3. Open a second terminal window and run `dask-worker tcp://172.16.1.113:8786 --nworkers 3 --nthreads 2 --memory-limit "2GB"`
(NOTE: You'll have to modify the IP address to whatever your LOCAL IP address is on the computer of the scheduler/your computer (so you're essentially connecting a `worker` on your machine, to the `scheduler` also on the same machine. you could have dask installed on many machines with the same version of python, and could connect them all to the same scheduler using the same command, but for this example, this will suffice). I have this set to use `3` processes/cores, `2` threads per core, and a memory limit of `2GB` per process/core. This is based on my machine's specs, you can adjust accordingly. Then run this script:

```
from time import sleep
from dask import compute, delayed
from distributed import Client

# Connect to dask scheduler
client = Client("tcp://172.16.1.113:8786")

# Define a dummy function to run
def scoring_function(i, number):
    sleep(5)
    print(i)
    return number**2

# Store some future calculations in a list
delayed_results = []

# Iterate through some numbers and add the futures to the list
for i, number in zip(range(0,5), range(0,5)):
    delayed_results.append(delayed(scoring_function)(i, number))

# Compute the futures using your cluster
result = compute(*delayed_results)
print(result)
```

So that's the flow of how things SHOULD operate, and I feel like I'm close with my implementation for PyGAD to make use of Dask, however I need to figure this bug out as I'm stuck. It could be a distributed issue, not liking the `fitness_func` functions as part of the delayed computation, or it could be my previously mentioned pickleable issue, however opening an issue there wouldn't do much good as this is pertaining more to PyGAD than anything. 

Anyway, if you're interested, take a look and let me know what you think/if you have any debug suggestions! Thanks!!!!

**Comment by windowshopr** [comment]
I will add that, in order to trigger that code in an example problem, you would create your PyGAD object like so:

```
    client = Client("tcp://172.16.1.113:8786")

    ga_instance = pygad.GA(num_generations=50,
                        num_parents_mating=7,
                        sol_per_pop=50,
                        gene_space=gene_space,
                        num_genes=len(gene_space),
                        fitness_func=fitness_func,
                        on_generation=callback_generation,
                        suppress_warnings=True,
                        parallel_processing=client
                        )
```

...and you should see the error. Maybe? haha

**Comment by windowshopr** [comment]
Ok, I have a more complete working example of how to run PyGAD with Dask below. Sorry, It was a late night last night so my previous messages were likely a little confusing haha my apologies. Here is a step-by-step guide on how to get this working (At least, on Windows 10, Python 3.10.5)

1. Update `pygad.py` with my fork [here](https://github.com/windowshopr/GeneticAlgorithmPython/blob/master/pygad.py).
2. Run `pip install dask[complete]` (I think this is all you need, might have to also install `distributed`, but I think it's included in the install)
3. Open a terminal window and run dask-scheduler to start the scheduler
Open a second terminal window and run dask-worker tcp://172.16.1.113:8786 --nworkers 3 --nthreads 2 --memory-limit "2GB"
(NOTE: You'll have to modify the IP address to whatever your LOCAL IP address is on the computer of the scheduler/your computer (so you're essentially connecting a worker on your machine, to the scheduler also on the same machine. you could have dask installed on many machines with the same version of python, and could connect them all to the same scheduler using the same command, but for this example, this will suffice). I have this set to use 3 processes/cores, 2 threads per core, and a memory limit of 2GB per process/core. This is based on my machine's specs, you can adjust accordingly. 
4. Navigate to `http://127.0.0.1:8787/status` to see your Dask dashboard and connected workers
5. Run this example script and monitor the Dask dashboard! Code is well commented

```
from dask import compute, delayed
from distributed import Client
from sklearn.datasets import make_regression
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split
import pygad

# Define some global variables
EARLY_STOPPING_GENERATIONS = 5

# Create a mock regression dataset
X, y = make_regression(n_samples=1000,
                       n_features=50,
                       n_informative=20,
                       n_targets=1)

# Train-Test split the data
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.25,
                                                    random_state=0,
                                                    shuffle=False)

# Fitness function for PyGAD
def fitness_func(solution, solution_idx):
    
    # Deconstruct the common_params for the regressor from the current solution
    common_params = dict(learning_rate = solution[0],
                         n_estimators = int(solution[1]),
                         max_depth = int(solution[2]),
                         min_samples_leaf = int(solution[3]),
                         min_samples_split = int(solution[4]),
                         )
    
    # Create a regressor using the current solution's hyperparams
    gbr = GradientBoostingRegressor(loss="absolute_error", 
                                    **common_params, 
                                    random_state=0)
    
    # Train the regressor
    gbr.fit(X_train, y_train)
    
    # Test the regressor. Return negative Absolute Error
    fitness = -gbr.score(X_test, y_test)
    
    # Return the fitness score
    return fitness

# Create a gene space of hyperparms for the GradientBoostingRegressor and PyGAD
gene_space = [
    {"low": 0.001, "high": 0.10005, "step": 0.00005}, # learning_rate
    {"low": 50, "high": 550, "step": 50}, # n_estimators
    {"low": 1, "high": 11, "step": 1}, # max_depth
    {"low": 2, "high": 22, "step": 2}, # min_samples_leaf
    {"low": 2, "high": 22, "step": 2}, # min_samples_split
]

# Create a generation callback to check for early stopping
last_fitness = 0
best_fitness = 0
current_early_stopping_gen_count = 0
def callback_generation(ga_instance):
    global last_fitness, best_fitness, current_early_stopping_gen_count
    print("Generation = {generation}".format(generation=ga_instance.generations_completed))
    print("Fitness    = {fitness}".format(fitness=ga_instance.best_solution()[1]))
    print("Change     = {change}".format(change=ga_instance.best_solution()[1] - last_fitness))
    print("Best solution = ", ga_instance.best_solution()[0])
    last_fitness = ga_instance.best_solution()[1]
    # Update the current best fitness score and reset the early stopping counter
    if last_fitness > best_fitness:
        best_fitness = last_fitness
        current_early_stopping_gen_count = 0
    else:
        current_early_stopping_gen_count += 1
    # If we've hit the max early stopping gen rounds, stop!
    if current_early_stopping_gen_count >= EARLY_STOPPING_GENERATIONS:
        print("EARLY STOPPPING ENGAGED!")
        return 'stop'

# Connect to your dask scheduler
client = Client("tcp://172.16.1.113:8786")

# Create the GA instance
ga_instance = pygad.GA(num_generations=50, # Early stopping is used, so this can be a big number if desired
                    num_parents_mating=3,
                    sol_per_pop=10,
                    gene_space=gene_space,
                    num_genes=len(gene_space),
                    fitness_func=fitness_func,
                    on_generation=callback_generation,
                    suppress_warnings=True,
                    parallel_processing=client, # ["process", 4], client
                    )

# Run the GA instance
ga_instance.run()

# Display the best solution info
print(ga_instance.best_solution())
```

You'll now see your workers engaged on the Dask dashboard. The scheduler sends individual solutions from the current generation to each one of your worker processes/machines connected to the scheduler. I have 3 computers connected to my scheduler with a total of 10 processes, so I can run 10 `fitness_func`'s at one time across multiple machines, not just 1. Woohoo!

So feel free to test this on your end and update if you think it's necessary :) I'm still stuck trying to debug my error in my particular use case and it has to do with something not being serializable with pickle, so I'll have to figure that out on my end, but this can work as an example for a new update :) Thanks!
